### ISSUE TITLE
Produce - How to Enable iCloud (Cloud Kit)

### ISSUE THREAD

**Issue by shahbazali** [KrauseFx/fastlane#712] opened 2015-10-20 12:47 UTC
Hi, i am using produce command to create APP ID on Developer Portal & iTunes that is working properly, but the issue is my application is using iCloud & i want to enable the iCloud with Cloud Kit, is there a way i can add in my following code? if Yes please Help

produce(
    username: 'abcabc@gmail.com',
    app_identifier: 'com.example.shahbaz',
    app_name: 'EXAMPLE NAME',
    language: 'English',
    app_version: '1.0',
    sku: 'com.example.shahbaz',
    team_name: 'MY TEAM NAME' 
  )

Secondly, when i use this (   produce enable_services --icloud cloudkit ) command after produce statement it enables iCloud on Developer Portal but did not created iCloud Container & its association. 

Please Help. 
Thanks

**Comment by shahbazali** [comment] 2015-10-21 13:39
Please Answer

**Comment by KrauseFx** [comment] 2015-10-23 22:07
Duplicate of https://github.com/fastlane/produce/issues/81#issuecomment-148947513

**Closed by KrauseFx** 2015-10-23 22:07 UTC

**Comment by shahbazali** [comment] 2015-10-25 13:05
Hello, I'm sorry i disturbed you again but its not working for me, as i am using 
produce enable_services --icloud cloudkit 
that works fine, but the issue is iCloud Container is not creating through this command, it give message 1 Service Enabled Successfully, but when i go to Developer Portal iCloud always says Configurable because Container is not created. 

thanks in advance.
