### ISSUE TITLE
“gem install bundler” invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by HurtleHD** [KrauseFx/fastlane#628] opened 2015-09-24 00:31 UTC
Hello I keep seeing a fix for this, And it involves putting this

export LANG="C.UTF-8"
export LC_ALL="C.UTF-8"

Can someone tell me how to do this?

**Comment by HurtleHD** [comment] 2015-09-24 00:55
@KrauseFx

**Comment by KrauseFx** [comment] 2015-09-24 04:12
Add this to your `~/.bash_profile `

```sh
export LANG="C.UTF-8"
export LC_ALL="C.UTF-8"
```

and restart your Terminal.

**Comment by HurtleHD** [comment] 2015-09-24 16:56
@KrauseFx Sorry to bother, Its that im kinda new,, How do i add that to my bundler, 

Thats the gem im trying to install

**Comment by KrauseFx** [comment] 2015-09-24 17:18
You don't need to add this to your bundler, you need to add this to your `~/.bash_profile` file

**Comment by HurtleHD** [comment] 2015-09-24 17:21
Okay, every-time i run the command i get this.   "No such file or directory"

**Comment by KrauseFx** [comment] 2015-09-24 17:35
Oh, it's not a command. You need to edit the text file at `~/.bash_profile`, e.g. `nano ~/.bash_profile` and then add the 2 lines I posted above :+1:

**Comment by HurtleHD** [comment] 2015-09-24 17:37
ugh illl drop this. i cant seem to figure this out thanks though sorry for wasting your time. 

Cant seem to find where bash_profile is

**Comment by HurtleHD** [comment] 2015-09-24 17:48
@KrauseFx ![untitled](https://cloud.githubusercontent.com/assets/14813453/10081437/e5463b1e-62c2-11e5-9003-ba4eff3ce3bd.png)

**Comment by KrauseFx** [comment] 2015-09-24 18:23
It seems like you're on the wrong repo. This is the `fastlane` repo which is a tool for iOS developers. 

Duplicate of https://github.com/KrauseFx/fastlane/issues/627

How did you come to this repo when trying to install something on your iPad?

**Comment by HurtleHD** [comment] 2015-09-24 19:29
@KrauseFx Dont really know. Just clicked on new issue... Is there a way u can move this to the right repo?

**Comment by KrauseFx** [comment] 2015-09-24 20:05
@HurtleHD Sorry, that's not how GitHub works. I have nothing to do with the thing you want to do with your iPad.

**Closed** 2015-09-24 20:05 UTC
