### ISSUE TITLE
`Fastlane -v` takes very long to execute

### ISSUE THREAD

**Issue by dbachrach** [KrauseFx/fastlane#310] opened 2015-05-21 17:23 UTC
I've been noticing that fastlane seems to take a long time to execute. The worst case I've seen-- 50 seconds:

```bash
➜  ~  time fastlane -v
fastlane 1.2.3
fastlane -v  50.62s user 1.67s system 99% cpu 52.499 total
```

Coworker machines are also taking long (roughly 10 seconds each time).

Are others experiencing this delay, or is it maybe isolated to our systems? Let me know what information would be useful to provide.

**Comment by KrauseFx** [comment] 2015-05-21 17:27
Unfortunately this seems to be related to RubyGems or Bundler, I can't really tell. As far as I know there is not much I can do :disappointed: If you have an idea how to speed this up, please let me know.

It usually runs much faster when running it using `bundle exec` when you used Bundler.

**Comment by dbachrach** [comment] 2015-05-21 17:49
> It usually runs much faster when running it using bundle exec when you used Bundler.

Can confirm this is true.

**Comment by KrauseFx** [comment] 2015-07-16 22:06
I'll close this issue for now, as I don't know if it's an issue caused by `fastlane` or Ruby. Also, probably related https://github.com/KrauseFx/fastlane/issues/420

**Closed by KrauseFx** 2015-07-16 22:06 UTC

**Comment by besi** [comment] 2015-08-19 03:36
Same problem here, it takes two minutes to display the version (!):

```bash
$ time fastlane --version
fastlane 1.18.0

real	2m2.848s
user	1m54.236s
sys	0m5.715s
```

**Comment by KrauseFx** [comment] 2015-08-19 08:36
Sorry about that @besi, but there is not much I can do except adding notes to the documentation.

**Comment by besi** [comment] 2015-08-19 09:47
@krausefx: not a problem. I just thought I post my case and copy the solution into this issue.
