### ISSUE TITLE
commit_version_bump action errors with "Could not find option for key :force"

### ISSUE THREAD

**Issue by wireframe** [KrauseFx/fastlane#226] opened 2015-04-23 04:25 UTC
I'm not passing `force` as an option to the `commit_version_bump` action, so not sure what to do about this error message.

Fastfile:
```ruby
# This block is called, only if the executed lane was successful
after_all do |lane|
  commit_version_bump
  add_git_tag
  push_to_git_remote
  slack(
    message: "Successfully built lane: #{lane}",
    success: true,
    channel: 'workshop'
  )
end
```

Error log:
```
INFO [2015-04-22 23:20:50.21]: ---------------------------------
INFO [2015-04-22 23:20:50.21]: --- Step: commit_version_bump ---
INFO [2015-04-22 23:20:50.21]: ---------------------------------
INFO [2015-04-22 23:20:50.50]: Variable Dump: FILTERED
FATAL [2015-04-22 23:20:50.50]: Could not find option for key :force. Available keys: message, xcodeproj
FATAL [2015-04-22 23:20:51.25]: fastlane finished with errors
/Users/ryansonnek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fastlane_core-0.6.2/lib/fastlane_core/configuration.rb:69:in `fetch': Could not find option for key :force. Available keys: message, xcodeproj (RuntimeError)
	from /Users/ryansonnek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.12.4/lib/fastlane/actions/commit_version_bump.rb:60:in `run'
	from /Users/ryansonnek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.12.4/lib/fastlane/fast_file.rb:112:in `block (2 levels) in method_missing'
	from /Users/ryansonnek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.12.4/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/ryansonnek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.12.4/lib/fastlane/fast_file.rb:94:in `block in method_missing'
	from /Users/ryansonnek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.12.4/lib/fastlane/fast_file.rb:93:in `chdir'
	from /Users/ryansonnek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.12.4/lib/fastlane/fast_file.rb:93:in `method_missing'
	from (eval):65:in `block (2 levels) in parse'
	from /Users/ryansonnek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.12.4/lib/fastlane/runner.rb:40:in `call'
	from /Users/ryansonnek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.12.4/lib/fastlane/runner.rb:40:in `block in execute'
	from /Users/ryansonnek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.12.4/lib/fastlane/runner.rb:24:in `chdir'
	from /Users/ryansonnek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.12.4/lib/fastlane/runner.rb:24:in `execute'
	from /Users/ryansonnek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.12.4/lib/fastlane/lane_manager.rb:33:in `cruise_lane'
	from /Users/ryansonnek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.12.4/bin/fastlane:39:in `block (2 levels) in run'
	from /Users/ryansonnek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.3/lib/commander/command.rb:178:in `call'
	from /Users/ryansonnek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.3/lib/commander/command.rb:178:in `call'
	from /Users/ryansonnek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.3/lib/commander/command.rb:153:in `run'
	from /Users/ryansonnek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.3/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/ryansonnek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.3/lib/commander/runner.rb:68:in `run!'
	from /Users/ryansonnek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/commander-4.3.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/ryansonnek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.12.4/bin/fastlane:118:in `run'
	from /Users/ryansonnek/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-0.12.4/bin/fastlane:124:in `<top (required)>'
	from bin/fastlane:16:in `load'
	from bin/fastlane:16:in `<main>'
```

**Comment by milch** [comment] 2015-04-24 15:45
Apparently during the transition to the new config format this parameter was forgotten. 

However, in your case, the problem is actually another one: since you are running `commit_version_bump` in the `after_all` block, your git status will most likely be dirty. Try moving it into `before_all` or, alternatively, running the `clean_build_artifacts` action before running `commit_version_bump` should work as well.

**Comment by wireframe** [comment] 2015-04-24 15:47
you're correct.  my git repo was dirty and adding `clean_build_artifacts` beforehand did fix the issue.

**Closed** 2015-04-25 14:16 UTC

**Comment by KrauseFx** [comment] 2015-04-25 17:29
Thanks again @milch for providing a pull request resolving this issue. In fact, I really forgot to migrate this option and it seems like there was no test for this available parameter.
