### ISSUE TITLE
error after update sigh 0.6.0

### ISSUE THREAD

**Issue by HongliYu** [KrauseFx/fastlane#348] opened 2015-06-11 05:56 UTC
➜  BaiduBrowser  fastlane -v
/Library/Ruby/Site/2.0.0/rubygems/specification.rb:2100:in `check_version_conflict': can't activate mime-types-2.6.1, already activated mime-types-1.25.1 (Gem::LoadError)
	from /Library/Ruby/Site/2.0.0/rubygems/specification.rb:1276:in `activate'
	from /Library/Ruby/Site/2.0.0/rubygems.rb:216:in `block in finish_resolve'
	from /Library/Ruby/Site/2.0.0/rubygems.rb:215:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems.rb:215:in `finish_resolve'
	from /Library/Ruby/Site/2.0.0/rubygems/rdoc.rb:14:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/commands/update_command.rb:9:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.2/lib/fastlane/actions/update_fastlane.rb:2:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.2/lib/fastlane/actions/actions_helper.rb:129:in `block in load_default_actions'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.2/lib/fastlane/actions/actions_helper.rb:128:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.2/lib/fastlane/actions/actions_helper.rb:128:in `load_default_actions'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.2/lib/fastlane.rb:21:in `<module:Fastlane>'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.2/lib/fastlane.rb:18:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.3.2/bin/fastlane:5:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'

**Comment by KrauseFx** [comment] 2015-06-11 12:02
Duplicate of https://github.com/KrauseFx/fastlane/issues/249

Please try `sudo gem cleanup`.

**Closed by KrauseFx** 2015-06-11 12:02 UTC

**Comment by MarkMolina** [comment] 2015-07-06 09:14
cleanup unfortunately doesn't work for me

```
Cleaning up installed gems...
Clean Up Complete
```

Used to work fine before update

**Comment by scibidoo** [comment] 2015-07-06 22:13
@KrauseFx I've followed some of the previous posts and of course tried the gem cleanup, the problem continued. I resorted to removing all of the components for fastlane individually and reinstalling them again. Nokigiri failing to install caused problems with completing the fastlane install and that required another workaround. I am now able to perform fastlane --v without any errors ;)

**Comment by KrauseFx** [comment] 2015-07-07 07:07
@scibidoo really sorry for the troubles. I always try to improve the installation process, but because of `nokogiri` it's often quite difficult :disappointed:
