### ISSUE TITLE
Sigh: Lane specific `team_id` and `app_identifier` not used

### ISSUE THREAD

**Issue by kommen** [KrauseFx/fastlane#256] opened 2015-05-05 13:51 UTC
With fastlane `0.13.0` in my `Appfile`

```
app_identifier "appid1"
team_id "team1"

for_lane :enterprise do
  app_identifier "appid2"
  team_id "teamid2"
end
```

But in the `enterprise` lane sigh uses the global `appid1` instead of `appid2`. This worked with `0.7.0`.

**Comment by KrauseFx** [comment] 2015-05-05 13:56
Sorry, I forgot to add this to the migration guide. With the most recent version I introduced a change to how lanes work. Please see the updated documentation: https://github.com/KrauseFx/fastlane/blob/master/docs/Advanced.md#the-appfile

Basically you now use a string instead of a symbol. In case you also have a platform declaration in your `Fastfile` you can add this to your name as well.

This was probably not a very great decision from my side. I guess something like this would have been better:

```ruby
for_platform :ios do
  for_lane :enterprise do
    app_identifier 'com.app'
  end
end
```

More information about the multi platform support: https://github.com/KrauseFx/fastlane/releases/tag/0.11.0

What do you think? Should I change to the above posted code instead of having a string?

**Comment by KrauseFx** [comment] 2015-05-05 13:56
This would also enable things like:

```ruby
for_platform :ios do
  team_id '123' # for all iOS related things
  for_lane :enterprise do
    app_identifier 'com.app'
  end
end
```

**Comment by kommen** [comment] 2015-05-05 14:08
Yep, using a string instead of a symbol makes it work again. Thanks!

But yeah, I would prefer the `for_platform` approach like you suggested.

**Comment by KrauseFx** [comment] 2015-05-05 15:13
I'll fix this right now, thanks again :+1:

**Comment by KrauseFx** [comment] 2015-05-05 15:22
@fabiomassimo will work on this over the next few days/weeks :rocket:

**Comment by fabiomassimo** [comment] 2015-05-18 09:35
This upgrade has been implemented through:

## Fastlane : https://github.com/KrauseFx/fastlane/pull/295

## Credentials Manager https://github.com/fastlane/CredentialsManager/pull/7:

**Comment by kommen** [comment] 2015-05-18 09:49
Thanks @fabiomassimo!

**Comment by SpacyRicochet** [comment] 2015-05-20 14:41
Using fastlane 1.2.2 I'm still having issues with this. I'm using the following Appfile:

```
apple_id "bruno@noodlewerk.com"
app_identifier "com.somecompany.someapp-ios-ios"
app_name "Some App"

for_lane :beta do
    app_identifier 'com.somecompany.someapp-ios.adhoc'
    team_name 'Some Company.nl B.V.'
end
```

However, `sigh` keeps asking for my Apple ID and later on for my bundle identifier. Any reason for why it doesn't seem to look in the Appfile at all?

**Comment by fabiomassimo** [comment] 2015-05-20 14:53
Hi @SpacyRicochet,
Thanks for your feedback.
The issue is due to the fact that Credentials Manager 0.5.0 (shipped with fastlane 1.2.2) does not include latest changes required to get this feature work.
I've already talked with @KrauseFx and he will include the new Credentials Manager version in next fastlane release.

**Comment by SpacyRicochet** [comment] 2015-05-20 15:14
@fabiomassimo Thanks for the information. Will be eagerly awaiting the new version then :)

**Comment by fabiomassimo** [comment] 2015-05-20 15:20
@SpacyRicochet Thanks for your patience.

**Comment by KrauseFx** [comment] 2015-05-20 16:01
Sorry for the short delay, university exams take up some time :disappointed: 
Just pushed the new release: https://github.com/fastlane/CredentialsManager/releases/tag/0.6.0

Please update using `sudo gem update credentials_manager` :+1:

**Comment by KrauseFx** [comment] 2015-05-20 16:01
Thanks again @fabiomassimo for working on this :rocket: great job! :+1:

**Comment by SpacyRicochet** [comment] 2015-05-21 09:18
Still doesn't seem to catch anything in the Appfile. sigh still starts me off by asking for my username (`apple_id`), even though it's defined in my Appfile (see above). It shouldn't be the multi-platform support, since my `apple_id` is defined outside of that.

```
[11:00:25]: ------------------
[11:00:25]: --- Step: sigh ---
[11:00:25]: ------------------
[11:00:27]: Login into iOS Developer Center
No username or password given. You can set environment variables:
DELIVER_USER, DELIVER_PASSWORD
-------------------------------------------------------------------------------------
The login information you enter will be stored in your Mac OS Keychain
More information about that on GitHub: https://github.com/fastlane/CredentialsManager
-------------------------------------------------------------------------------------
Username: 
```

Any ideas? Or, any way to check if the Appfile is being read properly?

**Comment by fabiomassimo** [comment] 2015-05-21 09:24
I have run your Appfile in our test cases and Credentials Manager parse it as expected.
Could you paste here the environment variables that fastlane prints out at very beginning of the process?

**Comment by KrauseFx** [comment] 2015-05-21 09:27
@fabiomassimo 

> Could you paste here the environment variables that fastlane prints out at very beginning of the process?

Where does it do that? What do you mean?

**Comment by fabiomassimo** [comment] 2015-05-21 09:39
Sorry somehow I remember fastlane printed out the environment variables at every iteration. I must be wrong.
I'll look into this later today.

**Comment by ben-lings-tessella** [comment] 2015-05-28 11:59
I'm seeing what looks like the same problem. I have a `Fastfile` that's configured without multi-platform support (i.e. no `default_platform` or `platform :ios do`). In the `Appfile` I have only `for_lane do` blocks (no `for_platform do`). The blocks don't get called (I've added `puts` statements to check).

From what I can tell (looking at [credentials manager]( https://github.com/fastlane/credentials_manager/blob/9b59728c54d248ff59a14f6314d6aec5b922d3de/lib/credentials_manager/appfile_config.rb#L124) ), it's trying to run a platform block that doesn't exist. The value of `ENV["FASTLANE_PLATFORM_NAME"]` is an empty string when the `Appfile` is `eval`'d

**Comment by ben-lings-tessella** [comment] 2015-05-28 12:03
I've worked around this by adding a
```
for_platform "" do 
  # ...
end
```
block around the `for_lane` blocks.

**Comment by fabiomassimo** [comment] 2015-05-28 12:31
Thanks for your feedback I had sometime to spend on it yesterday and I found the bug. I'm working on the PR.
Stay tuned for next fastlane release :)

**Comment by KrauseFx** [comment] 2015-07-16 22:02
@fabiomassimo What's the current status on this?

**Comment by fabiomassimo** [comment] 2015-07-18 10:09
I took care of it in #325 
I'd love to hear back from @ben-lings-tessella or @SpacyRicochet about this.

**Comment by KrauseFx** [comment] 2015-07-18 10:12
I'll close this issue for now, thanks @fabiomassimo :+1:

**Closed by KrauseFx** 2015-07-18 10:12 UTC
Labels: enhancement

**Comment by SpacyRicochet** [comment] 2015-07-21 12:29
Sorry about not checking back here. It works fine :) Thanks @fabiomassimo!
