### ISSUE TITLE
Issues with password

### ISSUE THREAD

**Issue by tilowestermann** [KrauseFx/fastlane#39] opened 2015-02-11 10:22 UTC
Setting up the Deliverfile, I encountered the following error. It appeared after I entered the the wrong iTunes Connect credentials (I was asked wether I wanted to reenter my credentials, which I answered with yes).

```
You will have to re-run the recent command to use the new username/password.
DEBUG [2015-02-11 11:15:12.40]: [Transporter Output]: DBG-X: The error code is: -20101
FATAL [2015-02-11 11:15:12.40]: Transporter transfer failed.
WARN [2015-02-11 11:15:12.40]: 
ERROR [2015-02-11 11:15:12.40]: Your Apple ID or password was entered incorrectly. (-20101)
FATAL [2015-02-11 11:15:12.40]: Return status of iTunes Transporter was 1: Your Apple ID or password was entered incorrectly. (-20101)
ERROR [2015-02-11 11:15:12.40]: Your Apple ID or password was entered incorrectly. (-20101)
Return status of iTunes Transporter was 1: Your Apple ID or password was entered incorrectly. (-20101)
FATAL [2015-02-11 11:15:12.40]: Could not download metadata from iTunes Connect. Do you have special characters in your password (Like ' or ")?
FATAL [2015-02-11 11:15:12.40]: Error occured with the setup program! Reverting changes now!
INFO [2015-02-11 11:15:12.40]: Deleting the 'fastlane' folder

/usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.7.6/lib/deliver/app_metadata.rb:302:in `read': No such file or directory @ rb_sysopen - /tmp/527216534.itmsp//metadata.xml (Errno::ENOENT)
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.7.6/lib/deliver/app_metadata.rb:302:in `parse_package'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.7.6/lib/deliver/app_metadata.rb:66:in `initialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.7.6/lib/deliver/app.rb:113:in `new'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.7.6/lib/deliver/app.rb:113:in `metadata'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.7.6/lib/deliver/deliverfile/deliverfile_creator.rb:59:in `create_based_on_identifier'
	from /usr/local/lib/ruby/gems/2.2.0/gems/deliver-0.7.6/lib/deliver/deliverfile/deliverfile_creator.rb:30:in `create'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-0.1.7/lib/fastlane/setup.rb:82:in `ask_to_enable_other_tools'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-0.1.7/lib/fastlane/setup.rb:17:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-0.1.7/bin/fastlane:44:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.2.1/lib/commander/command.rb:180:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.2.1/lib/commander/command.rb:180:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.2.1/lib/commander/command.rb:155:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.2.1/lib/commander/runner.rb:421:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.2.1/lib/commander/runner.rb:81:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.2.1/lib/commander/delegates.rb:8:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-0.1.7/bin/fastlane:59:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-0.1.7/bin/fastlane:63:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by tilowestermann** [comment] 2015-02-11 10:31
I tried it again and copied the password from my password manager to make sure that it is correct. Same error. Probably related to #9, although my password doesn't start with a dash (and it doesn't include quotation marks).

**Comment by KrauseFx** [comment] 2015-02-11 11:11
Thanks, I'll take a look into it. Since you want to set up `deliver`, can you start by only running `deliver init` and see if you run into the same problem?

**Comment by tilowestermann** [comment] 2015-02-11 11:15
Thanks for the quick reply. Running `deliver init` produces the same error. So this issue should be moved to the deliver project.

**Comment by KrauseFx** [comment] 2015-02-11 11:16
Okay. So this has to do with your password. This is still a pain and there are some issues about this already: https://github.com/krausefx/deliver/issues?q=password

I haven't found a good solution to make it work :disappointed:

**Comment by tilowestermann** [comment] 2015-02-11 11:20
Oh, I see. So having a bad password is actually good ;-)

**Comment by aafa** [comment] 2015-02-18 12:43
Can confirm.  Having special characters in password is leading to this error. Alpha-numeric password works fine.

**Comment by dtrenz** [comment] 2015-02-25 16:49
+1 Also, having this issue with a password that contains the following non-alphanumeric chars: [?{,$=+(

**Comment by KrauseFx** [comment] 2015-03-09 00:18
I'll close the issue as duplicate of https://github.com/KrauseFx/deliver/issues/79 in the `deliver` branch. Sorry about the hassles :disappointed:

**Closed by KrauseFx** 2015-03-09 00:18 UTC

**Comment by KrauseFx** [comment] 2016-02-12 19:08
We just pushed a new release https://github.com/fastlane/fastlane_core/releases/tag/0.36.4
Could you give it a try by updating using
```
sudo gem update fastlane_core`
```
or `bundle update` if you're using bundler

Let me know if that solves your problem :+1:
