### ISSUE TITLE
Fastlane init: password starting with a dash is interpreted as a command option

### ISSUE THREAD

**Issue by bartvandendriessche** [KrauseFx/fastlane#9] opened 2015-01-19 08:50 UTC
Noticed this while playing around with fastlane and running `fastlane init` as described in the GUIDE.

I have an iTunesConnect password that starts with a dash, and got the following warning after which the process stopped:

```
[Transporter Warning Output]: The following option was specified but is not recognized:<-my-password-starting-with-a-dash>
```

**Comment by KrauseFx** [comment] 2015-01-19 09:24
Mh, I'm escaping the password properly when passing to the transporter: [itunes_transporter.rb:19](https://github.com/KrauseFx/deliver/blob/master/lib/deliver/itunes_transporter.rb#L190)

Would it be possible for you to temporary change the password to not start with a `-`?

**Comment by bartvandendriessche** [comment] 2015-01-20 09:59
Yeah, I worked around it by using a different password, just thought you'd like to be aware, so I went ahead and created this issue.

**Comment by KrauseFx** [comment] 2015-03-08 16:55
I'll close this issue as duplicate of https://github.com/KrauseFx/fastlane/issues/39 and some others.

**Closed by KrauseFx** 2015-03-08 16:55 UTC
